/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.csystem.db.Personel;
import org.csystem.db.PersonelDAO;
import org.csystem.struts.form.PersonelForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-18-2012
 * 
 * XDoclet definition:
 * @struts.action path="/personel" name="personelForm" input="/form/personel.jsp" scope="request" validate="true"
 */
public class PersonelAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		PersonelForm personelForm = (PersonelForm) form;// TODO Auto-generated method stub
		String ad = personelForm.getAd();
		PersonelDAO pDAO=new PersonelDAO();
		//List<Personel> personelList = pDAO.findAll();
		List<Personel> personelList = pDAO.findbyAd(ad);
		request.setAttribute("personelListesi", personelList);	
		return mapping.findForward("listele");
	}
}