/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.cdernek.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.cdernek.struts.form.UyeKontrolForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-10-2008
 * 
 * XDoclet definition:
 * @struts.action path="/uyeKontrol" name="uyeKontrolForm" input="/form/uyeKontrol.jsp" scope="request" validate="true"
 */
public class UyeKontrolAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UyeKontrolForm uyeKontrolForm = (UyeKontrolForm) form;// TODO Auto-generated method stub
		String user = uyeKontrolForm.getUser();
		String password = uyeKontrolForm.getPassword();
		if (user.equals("ahmet") && password.equals("123"))
			return mapping.findForward("basarili");
		return mapping.findForward("basarisiz");
	}
}