/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.cdernek.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.cdernek.hiber.Urun;
import org.cdernek.hiber.UrunDAO;
import org.cdernek.struts.form.UrunGirisForm;
import org.cdernek.hiber.Urun;
import org.hibernate.Transaction;
/** 
 * MyEclipse Struts
 * Creation date: 03-25-2011
 * 
 * XDoclet definition:
 * @struts.action path="/urunGiris" name="urunGirisForm" input="/urunGiris.jsp" scope="request" validate="true"
 */
public class UrunGirisAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UrunGirisForm urunGirisForm = (UrunGirisForm) form;// TODO Auto-generated method stub
		String urunAd = urunGirisForm.getUrunAd();
		String urunKod = urunGirisForm.getUrunAd();
		Integer fiyat = urunGirisForm.getFiyat();
		UrunDAO uD = new UrunDAO();
		Transaction trns=uD.getSession().beginTransaction();
		Urun urun=new Urun(urunAd, urunKod, fiyat);
		uD.save(urun);
		trns.commit();
		List<Urun> urunler = uD.findAll();		
		HttpSession session = request.getSession();
		session.setAttribute("urunler", urunler);
		return mapping.findForward("listele");
		
	}
}