/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

/**
 * MyEclipse Struts Creation date: 03-24-2012
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/personel" name="personelForm" input="/personel.jsp"
 *                scope="request" validate="true"
 */
public class PersonelAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm personelForm = (DynaActionForm) form;// TODO
															// Auto-generated
															// method stub

		return mapping.findForward("git");
	}
}