/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2012
 * 
 * XDoclet definition:
 * @struts.form name="personelForm"
 */
public class PersonelForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** email property */
	private String email;

	/** ad property */
	private String ad;

	/** soyad property */
	private String soyad;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the ad.
	 * @return String
	 */
	public String getAd() {
		return ad;
	}

	/** 
	 * Set the ad.
	 * @param ad The ad to set
	 */
	public void setAd(String ad) {
		this.ad = ad;
	}

	/** 
	 * Returns the soyad.
	 * @return String
	 */
	public String getSoyad() {
		return soyad;
	}

	/** 
	 * Set the soyad.
	 * @param soyad The soyad to set
	 */
	public void setSoyad(String soyad) {
		this.soyad = soyad;
	}
}