/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.UrunSecForm;

/** 
 * MyEclipse Struts
 * Creation date: 03-24-2012
 * 
 * XDoclet definition:
 * @struts.action path="/urunSec" name="urunSecForm" input="/uyeKontrol.jsp" scope="request" validate="true"
 */
public class UrunSecAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UrunSecForm urunSecForm = (UrunSecForm) form;// TODO Auto-generated method stub
		return null;
	}
}