/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import mydb.Customer;
import mydb.CustomerDAO;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.CustomerForm;

/**
 * MyEclipse Struts Creation date: 02-01-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/customer" name="customerForm" input="/customer.jsp"
 *                scope="request" validate="true"
 */
public class CustomerAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		CustomerForm customerForm = (CustomerForm) form;// TODO Auto-generated
														// method stub
		CustomerDAO cDAO = new CustomerDAO();
		List<Customer> customers = cDAO.findAll();
		request.setAttribute("customers", customers);
		return mapping.findForward("listele");
	}
}