/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionError;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.yourcompany.struts.form.RegisterForm;

/** 
 * MyEclipse Struts
 * Creation date: 02-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="registerForm" input="/register.jsp" scope="request" validate="true"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		RegisterForm registerForm = (RegisterForm) form;// TODO Auto-generated method stub
		String user = registerForm.getUser();
		if(user.trim().equals("Ahmet"))
		return mapping.findForward("git");
		ActionErrors errors=new ActionErrors();
		errors.add("hata", new ActionError("yanlis.giris"));
		saveErrors(request, errors);

		return mapping.findForward("basarisiz");
	}
}