/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package org.cdernek.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 03-25-2011
 * 
 * XDoclet definition:
 * @struts.form name="urunGirisForm"
 */
public class UrunGirisForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** fiyat property */
	private Integer fiyat;

	/** urunKod property */
	private String urunKod;

	/** urunAd property */
	private String urunAd;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the fiyat.
	 * @return Integer
	 */
	public Integer getFiyat() {
		return fiyat;
	}

	/** 
	 * Set the fiyat.
	 * @param fiyat The fiyat to set
	 */
	public void setFiyat(Integer fiyat) {
		this.fiyat = fiyat;
	}

	/** 
	 * Returns the urunKod.
	 * @return String
	 */
	public String getUrunKod() {
		return urunKod;
	}

	/** 
	 * Set the urunKod.
	 * @param urunKod The urunKod to set
	 */
	public void setUrunKod(String urunKod) {
		this.urunKod = urunKod;
	}

	/** 
	 * Returns the urunAd.
	 * @return String
	 */
	public String getUrunAd() {
		return urunAd;
	}

	/** 
	 * Set the urunAd.
	 * @param urunAd The urunAd to set
	 */
	public void setUrunAd(String urunAd) {
		this.urunAd = urunAd;
	}
}