/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-26-2014
 * 
 * XDoclet definition:
 * @struts.form name="urunGirForm"
 */
public class UrunGirForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** adet property */
	private String adet;

	/** ad property */
	private String ad;

	/** kod property */
	private String kod;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the adet.
	 * @return String
	 */
	public String getAdet() {
		return adet;
	}

	/** 
	 * Set the adet.
	 * @param adet The adet to set
	 */
	public void setAdet(String adet) {
		this.adet = adet;
	}

	/** 
	 * Returns the ad.
	 * @return String
	 */
	public String getAd() {
		return ad;
	}

	/** 
	 * Set the ad.
	 * @param ad The ad to set
	 */
	public void setAd(String ad) {
		this.ad = ad;
	}

	/** 
	 * Returns the kod.
	 * @return String
	 */
	public String getKod() {
		return kod;
	}

	/** 
	 * Set the kod.
	 * @param kod The kod to set
	 */
	public void setKod(String kod) {
		this.kod = kod;
	}
}