/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.yourcompany.struts.action;

import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.Globals;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.yourcompany.struts.form.DilSecForm;

/**
 * MyEclipse Struts Creation date: 02-01-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/dilSec" name="dilSecForm" input="/dilSec.jsp"
 *                scope="request" validate="true"
 */
public class DilSecAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DilSecForm dilSecForm = (DilSecForm) form;// TODO Auto-generated method
													// stub
		Locale l = null;
		String lang = request.getParameter("lang");
		if (lang.equals("eng"))
			l = new Locale("en", "US");
		else if (lang.equals("turk"))
			l = new Locale("tr", "TR");
		else if (lang.equals("german"))
			l = new Locale("de");

		HttpSession session = request.getSession();
		session.setAttribute(Globals.LOCALE_KEY, l);

		return mapping.findForward("kayit");

	}
}