//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.01 at 03:51:22 PM EET 
//


package ogr;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ogr package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VeliAd_QNAME = new QName("", "veliAd");
    private final static QName _Sinif_QNAME = new QName("", "sinif");
    private final static QName _Ad_QNAME = new QName("", "ad");
    private final static QName _DogYer_QNAME = new QName("", "dogYer");
    private final static QName _DogTar_QNAME = new QName("", "dogTar");
    private final static QName _Soyad_QNAME = new QName("", "soyad");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ogr
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OgrenciKayit }
     * 
     */
    public OgrenciKayit createOgrenciKayit() {
        return new OgrenciKayit();
    }

    /**
     * Create an instance of {@link Ogrenci }
     * 
     */
    public Ogrenci createOgrenci() {
        return new Ogrenci();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "veliAd")
    public JAXBElement<String> createVeliAd(String value) {
        return new JAXBElement<String>(_VeliAd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sinif")
    public JAXBElement<String> createSinif(String value) {
        return new JAXBElement<String>(_Sinif_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ad")
    public JAXBElement<String> createAd(String value) {
        return new JAXBElement<String>(_Ad_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dogYer")
    public JAXBElement<String> createDogYer(String value) {
        return new JAXBElement<String>(_DogYer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dogTar")
    public JAXBElement<String> createDogTar(String value) {
        return new JAXBElement<String>(_DogTar_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "soyad")
    public JAXBElement<String> createSoyad(String value) {
        return new JAXBElement<String>(_Soyad_QNAME, String.class, null, value);
    }

}
